/**
 * Who asked to be reminded, and when they were last here.
 *
 * SERVER ONLY — imports Redis. The browser's half is ./reminderClient.
 *
 * This is the first thing on the site that outlives a visit, which
 * ARCHITECTURE.md used to be able to say nothing did. It is worth being precise
 * about why: a reminder is a message sent to somebody who is not here, so
 * something has to know both how to reach them and that they are away. Neither
 * fact can live in their own browser, which is where everything else here lives.
 *
 * What it therefore holds, per subscriber, and nothing else: a push endpoint or
 * an email address, which edition they were practising, when they were last
 * seen, and how many nudges have gone out since. No name, no progress, no
 * history of what they answered. The id is generated by the browser and is the
 * only handle on the record — an unguessable 128-bit capability, which is what
 * lets somebody unsubscribe without an account to log in to.
 *
 * Optional like everything else: with no Redis configured, subscribing reports
 * failure and the prompt says reminders are unavailable, rather than accepting
 * an address it has nowhere to put.
 */
import { kv } from "./kv";
import { LOCALES, DEFAULT_LOCALE, type Locale } from "./content";

const PREFIX = "convi:rem";
const INDEX = `${PREFIX}:index`;
const recordKey = (id: string) => `${PREFIX}:sub:${id}`;

/**
 * A record with no heartbeat for this long deletes itself.
 *
 * Longer than the nudge ladder by a wide margin, so it is not doing the
 * ladder's job — it is the answer to "what happens to a push endpoint whose
 * browser was uninstalled two years ago".
 */
const RECORD_TTL_SECONDS = 400 * 24 * 60 * 60;

/** A browser's push subscription, as the Push API hands it over. */
export interface PushEndpoint {
  endpoint: string;
  keys: { p256dh: string; auth: string };
}

export interface ReminderRecord {
  /** Push subscription, or null for an email-only subscriber. */
  push: PushEndpoint | null;
  /** Email address, or null for a push-only subscriber. */
  email: string | null;
  locale: Locale;
  createdAt: number;
  lastSeen: number;
  lastSentAt: number | null;
  sentSinceSeen: number;
  /** Day streak as last reported by their browser. */
  streak: number;
}

/** Ids are opaque to us; this is only a shape check on something from outside. */
const ID_RE = /^[A-Za-z0-9_-]{16,64}$/;

export function validId(id: unknown): id is string {
  return typeof id === "string" && ID_RE.test(id);
}

export function remindersConfigured(): boolean {
  return kv !== null;
}

function knownLocale(value: unknown): Locale {
  return LOCALES.some((l) => l.locale === value) ? (value as Locale) : DEFAULT_LOCALE;
}

/**
 * A push endpoint, checked far enough to be worth storing.
 *
 * The URL has to be https and absolute because it is fetched later by the
 * sender; the two keys have to exist because the payload cannot be encrypted
 * without them.
 */
export function validPushEndpoint(value: unknown): PushEndpoint | null {
  if (!value || typeof value !== "object") return null;
  const sub = value as Record<string, unknown>;
  const endpoint = sub.endpoint;
  const keys = sub.keys as Record<string, unknown> | undefined;

  if (typeof endpoint !== "string" || endpoint.length > 1024) return null;
  try {
    if (new URL(endpoint).protocol !== "https:") return null;
  } catch {
    return null;
  }
  if (typeof keys?.p256dh !== "string" || typeof keys?.auth !== "string") return null;
  if (keys.p256dh.length > 256 || keys.auth.length > 128) return null;

  return { endpoint, keys: { p256dh: keys.p256dh, auth: keys.auth } };
}

export async function getRecord(id: string): Promise<ReminderRecord | null> {
  if (!kv) return null;
  try {
    return (await kv.get<ReminderRecord>(recordKey(id))) ?? null;
  } catch {
    return null;
  }
}

async function write(id: string, record: ReminderRecord): Promise<boolean> {
  if (!kv) return false;
  try {
    await kv.set(recordKey(id), record, { ex: RECORD_TTL_SECONDS });
    // Scored by last-seen, so the cron can ask for exactly the people who have
    // been away rather than reading every record to find out.
    await kv.zadd(INDEX, { score: record.lastSeen, member: id });
    return true;
  } catch {
    return false;
  }
}

/**
 * Opting in, or adding a second channel to an existing opt-in.
 *
 * Merging rather than replacing: somebody who took push on their phone and then
 * gave an email on the same device meant both, and overwriting would silently
 * drop the one they chose first.
 */
export async function subscribe(
  id: string,
  input: { push?: PushEndpoint | null; email?: string | null; locale?: unknown; streak?: number }
): Promise<boolean> {
  const now = Date.now();
  const existing = await getRecord(id);

  const record: ReminderRecord = {
    push: input.push ?? existing?.push ?? null,
    email: input.email ?? existing?.email ?? null,
    locale: knownLocale(input.locale ?? existing?.locale),
    createdAt: existing?.createdAt ?? now,
    lastSeen: now,
    // A fresh opt-in starts the ladder over. Somebody who has just tapped
    // "remind me" is not two nudges into a silence.
    lastSentAt: null,
    sentSinceSeen: 0,
    streak: input.streak ?? existing?.streak ?? 0,
  };

  if (!record.push && !record.email) return false;
  return write(id, record);
}

/**
 * They are here. Resets the ladder, which is the only thing that does.
 *
 * A heartbeat for an id with no record is a no-op on purpose: it means somebody
 * unsubscribed, or made an id up. Creating a record from one would let anyone
 * fill the store with keys that can never be reached.
 */
export async function heartbeat(
  id: string,
  input: { locale?: unknown; streak?: number } = {}
): Promise<boolean> {
  const existing = await getRecord(id);
  if (!existing) return false;

  return write(id, {
    ...existing,
    locale: knownLocale(input.locale ?? existing.locale),
    lastSeen: Date.now(),
    lastSentAt: null,
    sentSinceSeen: 0,
    streak: input.streak ?? existing.streak,
  });
}

/** Records what went out, so the ladder advances and the gap is enforced. */
export async function recordNudgeSent(id: string, at = Date.now()): Promise<void> {
  const existing = await getRecord(id);
  if (!existing) return;
  await write(id, {
    ...existing,
    // The index score stays the last *seen* time, not the last send: the cron
    // asks "who has been away", and a nudge is not a visit.
    lastSeen: existing.lastSeen,
    lastSentAt: at,
    sentSinceSeen: existing.sentSinceSeen + 1,
  });
}

/** Opting out. Both channels at once — there is one X, not two. */
export async function unsubscribe(id: string): Promise<boolean> {
  if (!kv) return false;
  try {
    await kv.del(recordKey(id));
    await kv.zrem(INDEX, id);
    return true;
  } catch {
    return false;
  }
}

/** Drops a push endpoint the push service has told us is gone, keeping email. */
export async function dropPush(id: string): Promise<void> {
  const existing = await getRecord(id);
  if (!existing) return;
  if (!existing.email) {
    await unsubscribe(id);
    return;
  }
  await write(id, { ...existing, push: null, lastSeen: existing.lastSeen });
}

/**
 * Subscribers last seen before `before`, oldest first.
 *
 * Capped, because a cron run has a time limit and the oldest are the ones whose
 * ladder is furthest behind. Anybody missed is picked up by tomorrow's run.
 */
export async function staleSubscribers(
  before: number,
  limit = 300
): Promise<{ id: string; record: ReminderRecord }[]> {
  if (!kv) return [];

  let ids: string[] = [];
  try {
    ids = (await kv.zrange<string[]>(INDEX, 0, before, {
      byScore: true,
      offset: 0,
      count: limit,
    })) ?? [];
  } catch {
    return [];
  }

  const out: { id: string; record: ReminderRecord }[] = [];
  for (const id of ids) {
    const record = await getRecord(id);
    if (record) {
      out.push({ id, record });
    } else if (kv) {
      // The record expired but its index entry outlived it. Tidy up rather than
      // reading the same miss every night.
      try {
        await kv.zrem(INDEX, id);
      } catch {
        // Next run, then.
      }
    }
  }
  return out;
}

/** How many people are opted in — the one number the dashboard would want. */
export async function subscriberCount(): Promise<number> {
  if (!kv) return 0;
  try {
    return (await kv.zcard(INDEX)) ?? 0;
  } catch {
    return 0;
  }
}
