# The rest of the German word lists, as moments.

PLAN = {
    # ------------------------------------------------------------------
    "de-cuss-common": {
        # Kept as words: the polite one, one that would collide with Verdammt
        # as a second right answer, and an oath whose meaning is all tone.
        "keep": ["de-cuss-07", "de-cuss-08", "de-cuss-09"],
        "scenes": [
            scene(
                "de-cuss-sc-01", "de-cuss-01", "them",
                "The connection you were running for pulls out of the platform as you arrive.",
                "Das war unser Anschluss.", "That was our connection.",
                "Scheiße.", "Shit.",
                "Der nächste geht in zwanzig Minuten.", "The next one's in twenty minutes.",
                notes="The workhorse. Common enough to be barely rude, and still not for a job interview.",
                difficulty="easy",
            ),
            scene(
                "de-cuss-sc-02", "de-cuss-02", "them",
                "You get to the front of the queue and your card is in the other jacket.",
                "Nur Karte, kein Bargeld.", "Card only, no cash.",
                "Verdammt.", "Damn.",
                "Kein Problem, ich zahl.", "No problem — I'll pay.",
                difficulty="easy",
            ),
            scene(
                "de-cuss-sc-03", "de-cuss-03", "them",
                "It starts raining ten minutes into a walk and nobody brought a jacket.",
                "Und jetzt regnet's auch noch.", "And now it's raining too.",
                "So ein Mist.", "What a pain.",
                "Da vorne ist ein Café.", "There's a café up ahead.",
                notes="Mist is manure and lands about where 'crap' does. The one to reach for in front of somebody's parents.",
                difficulty="easy",
            ),
            scene(
                "de-cuss-sc-04", "de-cuss-06", "them",
                "Someone has spent ten minutes trying to explain the ticket machine to you.",
                "Und dann noch einmal von vorne.", "And now once more from the top.",
                "Mensch, jetzt hab ich's.", "Oh man — now I've got it.",
                "Na also.", "There you go.",
                notes="Completely safe in any company, including at work and in front of children. Frustration or affection, depending on the tone.",
                difficulty="easy",
            ),
            scene(
                "de-cuss-sc-05", "de-cuss-10", "them",
                "A friend tells you they swam across the lake and back before breakfast.",
                "Einmal rüber und wieder zurück.", "Across and back again.",
                "Donnerwetter!", "Well I never!",
                "War gar nicht so weit.", "It wasn't that far, really.",
                notes="Literally a thunderstorm. Admiration here; said flatly at somebody it is a telling-off, and both are old-fashioned in a likeable way.",
            ),
        ],
    },
    # ------------------------------------------------------------------
    "de-cuss-aggressive": {
        # Kept as words: a noun for a person, and two that the entries
        # themselves say belong to particular company.
        "keep": ["de-cuss-12", "de-cuss-15", "de-cuss-16"],
        "scenes": [
            scene(
                "de-cuss-sc-06", "de-cuss-04", "them",
                "Somebody has been talking over you for ten minutes and starts up again.",
                "Nein, jetzt hörst du mir mal zu.", "No — now you listen to me.",
                "Halt die Klappe.", "Shut it.",
                "Wie bitte?", "Excuse me?",
                notes="Genuinely rude. Among close friends it can be a joke; with anybody else it is the start of a row.",
                difficulty="hard",
            ),
            scene(
                "de-cuss-sc-07", "de-cuss-05", "them",
                "Someone has followed you down the street after being told twice to stop.",
                "Komm schon, sei nicht so.", "Come on, don't be like that.",
                "Verpiss dich.", "Piss off.",
                "Ist ja gut, ich geh.", "All right, I'm going.",
                notes="The strong one, and the one to keep for when you mean it. Lass mich in Ruhe does the same job without the swear.",
                difficulty="hard",
                women=True,
            ),
            scene(
                "de-cuss-sc-08", "de-cuss-11", "them",
                "Somebody at the bar will not take a polite no for an answer.",
                "Jetzt komm, ein Getränk nur.", "Come on — just one drink.",
                "Lass mich in Ruhe.", "Leave me alone.",
                "Schon gut.", "Fine.",
                notes="Not a swear word, and firmer for it. Clear enough that anybody listening knows exactly what was said.",
                difficulty="easy",
                women=True,
            ),
            scene(
                "de-cuss-sc-09", "de-cuss-13", "them",
                "A friend has made the same joke at your expense four times tonight.",
                "Und dann noch mal mit dem Akzent!", "And again with the accent!",
                "Das reicht jetzt.", "That's enough now.",
                "Okay, okay, ich hör auf.", "Okay, okay — I'll stop.",
                difficulty="easy",
            ),
            scene(
                "de-cuss-sc-10", "de-cuss-14", "them",
                "Your friend shows you the state of the kitchen after the party.",
                "Guck dir das mal an.", "Just look at this.",
                "Ach du Scheiße!", "Oh my god!",
                "Wir fangen oben an.", "We'll start at the top.",
                notes="Aimed at a situation, never at a person, which is what makes it safe where the others are not.",
            ),
        ],
    },
    # ------------------------------------------------------------------
    "de-flirt-safe": {
        # Kept as words: three that are observations about a person rather than
        # openings, and one that is a near-twin of a line taught here.
        "keep": ["de-flirt-12", "de-flirt-13", "de-flirt-14"],
        "scenes": [
            scene(
                "de-flirt-sc-01", "de-flirt-01", "them",
                "Someone you like arrives at the bar and takes their coat off.",
                "Sorry, ich bin spät.", "Sorry — I'm late.",
                "Du siehst gut aus.", "You look good.",
                "Danke, du aber auch.", "Thanks — so do you.",
                notes="The plain one, and it works. Gut aussehen is about how somebody looks tonight rather than a verdict on them.",
                difficulty="easy",
            ),
            scene(
                "de-flirt-sc-02", "de-flirt-02", "them",
                "They get flustered ordering and apologise for it.",
                "Sorry, ich bin durcheinander.", "Sorry — I'm all over the place.",
                "Du bist echt süß.", "You're really cute.",
                "Jetzt werd ich rot.", "Now you're making me blush.",
                difficulty="easy",
            ),
            scene(
                "de-flirt-sc-03", "de-flirt-03", "them",
                "Someone mentions they put the whole outfit together second-hand.",
                "Alles vom Flohmarkt, ehrlich.", "All from the flea market, honestly.",
                "Ich mag deinen Style.", "I like your style.",
                "Das freut mich.", "That's nice to hear.",
                difficulty="easy",
            ),
            scene(
                "de-flirt-sc-04", "de-flirt-04", "them",
                "They laugh at something you said and you want to say what you noticed.",
                "Du bist ja witzig.", "You're funny, you are.",
                "Du hast ein schönes Lächeln.", "You have a nice smile.",
                "Hör auf.", "Stop it.",
            ),
            scene(
                "de-flirt-sc-05", "de-flirt-05", "them",
                "You've been talking across a table with a candle on it for an hour.",
                "Warum guckst du so?", "Why are you looking at me like that?",
                "Du hast schöne Augen.", "You have beautiful eyes.",
                "Das sagst du nur so.", "You're just saying that.",
            ),
        ],
    },
    # ------------------------------------------------------------------
    "de-flirt-bolder": {
        # Kept as words: two closing lines with nothing to come back at them,
        # and one whose whole content is how tentative it is.
        "keep": ["de-flirt-17", "de-flirt-18", "de-flirt-20"],
        "scenes": [
            scene(
                "de-flirt-sc-06", "de-flirt-06", "them",
                "They ask, half joking, why you keep looking over.",
                "Warum guckst du eigentlich immer her?", "Why do you keep looking over here?",
                "Ich find dich echt attraktiv.", "I find you really attractive.",
                "Immerhin ehrlich.", "Honest, at least.",
            ),
            scene(
                "de-flirt-sc-07", "de-flirt-07", "them",
                "The group is splitting up and you'd like to see this one person again.",
                "Ich glaub, ich fahr dann heim.", "I think I'll head home, then.",
                "Hast du Lust auf ein Bier?", "Want to grab a beer?",
                "Gern, aber ein andermal.", "I'd like to — another time.",
            ),
            scene(
                "de-flirt-sc-08", "de-flirt-15", "them",
                "They ask what this actually is, directly, because it is late and nobody is pretending.",
                "Was ist das hier eigentlich?", "What is this, actually?",
                "Ich mag dich.", "I like you.",
                "Gut, dass du's sagst.", "Good that you said it.",
                notes="Mögen is to like and here it means it. Lieben is a long way further on and not a first-night word in German either.",
                difficulty="easy",
            ),
            scene(
                "de-flirt-sc-09", "de-flirt-16", "them",
                "The music has got loud enough that you're both shouting.",
                "Ich versteh kein Wort!", "I can't understand a word!",
                "Wollen wir woanders hingehen?", "Shall we go somewhere else?",
                "Ja, ich kenn was Ruhiges.", "Yes — I know somewhere quiet.",
            ),
            scene(
                "de-flirt-sc-10", "de-flirt-19", "them",
                "Their friends are at the door and you have about five seconds.",
                "Ich muss mit denen mit.", "I have to go with them.",
                "Gibst du mir deine Nummer?", "Can I have your number?",
                "Gib mir dein Handy.", "Give me your phone.",
                difficulty="easy",
            ),
        ],
    },
    # ------------------------------------------------------------------
    "de-flirt-respect": {
        # Kept as words: three closing courtesies with no reply to build on.
        "keep": ["de-flirt-21", "de-flirt-23", "de-flirt-24"],
        "scenes": [
            scene(
                "de-flirt-sc-11", "de-flirt-08", "them",
                "You've suggested carrying on somewhere else and they've gone quiet.",
                "Ich weiß nicht so recht…", "I'm not really sure…",
                "Kein Stress, wenn nicht.", "No pressure if not.",
                "Danke, das ist lieb.", "Thanks — that's kind.",
                women=True,
            ),
            scene(
                "de-flirt-sc-12", "de-flirt-09", "them",
                "They tell you they're seeing somebody already.",
                "Ich bin eigentlich vergeben.", "I'm actually seeing someone.",
                "Alles gut, ich respektiere das.", "All good — I respect that.",
                "Schön, dass wir geredet haben.", "Good that we talked.",
                difficulty="easy",
            ),
            scene(
                "de-flirt-sc-13", "de-flirt-22", "them",
                "They've given one-word answers twice and are looking at their phone.",
                "Sorry, ich bin heut nicht so da.", "Sorry — I'm not really here tonight.",
                "Ich lass dich in Ruhe.", "I'll leave you to it.",
                "Danke fürs Verständnis.", "Thanks for understanding.",
                notes="Leaving cleanly is the skill. Said once, without a sigh, and then actually done.",
                women=True,
            ),
            scene(
                "de-flirt-sc-14", "de-flirt-25", "them",
                "You read the evening as going one way and it was going another.",
                "Ich wollte echt nur reden.", "I honestly just wanted to talk.",
                "Sorry, hab ich falsch verstanden.", "Sorry — I misread that.",
                "Kein Ding.", "No big deal.",
            ),
            scene(
                "de-flirt-sc-15", "de-flirt-26", "them",
                "You realise you've been standing closer than they are comfortable with.",
                "Ein bisschen Platz wär gut.", "A bit of space would be good.",
                "Ich wollte nicht aufdringlich sein.", "I didn't mean to be pushy.",
                "Passt schon, danke.", "It's fine — thanks.",
                women=True,
            ),
        ],
    },
    # ------------------------------------------------------------------
    "de-flirt-consent": {
        # Kept as words: three that read the same in any moment and are worth
        # knowing on sight rather than producing on cue.
        "keep": ["de-flirt-10", "de-flirt-29", "de-flirt-32"],
        "scenes": [
            scene(
                "de-flirt-sc-16", "de-flirt-11", "them",
                "Their glass is empty and you're already halfway to standing up.",
                "Meins ist leer, glaub ich.", "Mine's empty, I think.",
                "Ist es okay, wenn ich dich auf einen Drink einlade?", "Is it okay if I buy you a drink?",
                "Ja, gern.", "Yes — please do.",
            ),
            scene(
                "de-flirt-sc-17", "de-flirt-27", "them",
                "You've put an arm along the back of the bench they're sitting on.",
                "Hmm…", "Hmm…",
                "Ist das okay für dich?", "Is this okay with you?",
                "Ja, ist schön.", "Yes — it's nice.",
                women=True,
                difficulty="easy",
            ),
            scene(
                "de-flirt-sc-18", "de-flirt-28", "them",
                "Their friends have arrived and the mood at the table has changed.",
                "Da sind meine Freundinnen.", "My friends are here.",
                "Soll ich gehen?", "Do you want me to go?",
                "Nein, bleib noch.", "No — stay a bit.",
                difficulty="easy",
            ),
            scene(
                "de-flirt-sc-19", "de-flirt-30", "them",
                "There's one free chair at the table and you've been talking across the room.",
                "Suchst du einen Platz?", "Looking for a seat?",
                "Darf ich mich setzen?", "May I sit down?",
                "Klar, setz dich.", "Of course — sit down.",
                difficulty="easy",
            ),
            scene(
                "de-flirt-sc-20", "de-flirt-31", "them",
                "They've been looking out of the window rather than at the party for a while.",
                "Ich brauchte kurz Luft.", "I just needed some air.",
                "Möchtest du lieber allein sein?", "Would you rather be on your own?",
                "Nur kurz, danke.", "Just for a moment — thanks.",
                notes="Offering the exit is the point. Asked once and accepted without an argument is the whole difference.",
                women=True,
            ),
        ],
    },
    # ------------------------------------------------------------------
    "de-berlin-words": {
        # Kept as words: a slash pair, the tag stuck on the end of everything,
        # and one of the two vintage words for brilliant — offering both as
        # answers would be a question with no wrong option.
        "keep": ["de-berlin-01", "de-berlin-05", "de-berlin-07"],
        "scenes": [
            scene(
                "de-berlin-sc-01", "de-berlin-02", "them",
                "Someone behind the Späti counter says something you don't catch.",
                "Wat solln det jetzt?", "What's that supposed to be?",
                "Wat hast du jesagt?", "What did you say?",
                "Ick sach, dit kostet zwei Euro.", "I said, that's two euros.",
                notes="Berlin turns was into wat and das into det, and it does it in nearly every sentence. Reading it is harder than hearing it.",
                region="berlin",
                difficulty="easy",
            ),
            scene(
                "de-berlin-sc-02", "de-berlin-03", "them",
                "You're at an Imbiss counter pointing at something you don't know the name of.",
                "Wat darf's sein?", "What'll it be?",
                "Det da, bitte.", "That one there, please.",
                "Kommt sofort.", "Coming right up.",
                notes="Det is Berlin's das. Pointing and saying det da will get you fed anywhere in the city.",
                region="berlin",
                difficulty="easy",
            ),
            scene(
                "de-berlin-sc-03", "de-berlin-04", "them",
                "A friend shows you the roof terrace that comes with their flat.",
                "Und det jehört alles zur Wohnung.", "And all this comes with the flat.",
                "Knorke!", "Brilliant!",
                "Wa? Hab ick Jlück jehabt.", "Right? I got lucky.",
                notes="Old Berlin, and still said — usually with a wink, because everybody knows how old it is.",
                region="berlin",
            ),
            scene(
                "de-berlin-sc-04", "de-berlin-06", "them",
                "Someone asks whether there's a direct train out to the lake on a Sunday.",
                "Jibt's da 'ne Direktverbindung?", "Is there a direct connection?",
                "Jibbet nich.", "Not happening.",
                "Dann eben umsteigen.", "We'll change, then.",
                notes="Gibt es nicht, in a Berlin mouth. The g goes to a j and the whole thing collapses into one word.",
                region="berlin",
                difficulty="hard",
            ),
            scene(
                "de-berlin-sc-05", "de-berlin-08", "you",
                "You spot something on the far side of the canal worth pointing out.",
                "Kiek ma, da drüben!", "Look at that, over there!",
                "Wo denn? Ach, ja!", "Where? Oh — yes!",
                notes="Guck mal, up here. Kieken is the Berlin verb for looking, and you will hear it before you ever need to say it.",
                region="berlin",
                difficulty="hard",
            ),
        ],
    },
    # ------------------------------------------------------------------
    "de-berlin-life": {
        # Kept as words: two nouns for a place and one for a thing, all of
        # which you point at rather than say.
        "keep": ["de-berlin-10", "de-berlin-13", "de-berlin-16"],
        "scenes": [
            scene(
                "de-berlin-sc-06", "de-berlin-09", "them",
                "It's two in the morning and the party has run out of everything.",
                "Wir haben nix mehr da.", "We've got nothing left.",
                "Ich geh zum Späti.", "I'll go to the Späti.",
                "Bring Chips mit.", "Bring crisps.",
                notes="The late-night corner shop, open when nothing else is, and the reason a Berlin evening never quite has to end.",
                region="berlin",
                difficulty="easy",
            ),
            scene(
                "de-berlin-sc-07", "de-berlin-11", "them",
                "You're at a Berlin bakery and the word you learned in Munich is the wrong one.",
                "Wat darf ick Ihnen jeben?", "Right, what are you after?",
                "Zwei Schrippen, bitte.", "Two bread rolls, please.",
                "Sonst noch wat?", "Anything else?",
                notes="A Schrippe in Berlin, a Semmel in Bayern, a Brötchen almost everywhere else. Same roll, and the word places you instantly.",
                region="berlin",
            ),
            scene(
                "de-berlin-sc-08", "de-berlin-12", "them",
                "You want a jam doughnut and the word for it here is not the word you expect.",
                "Wat möchten Se denn?", "What would you like?",
                "Einen Pfannkuchen, bitte.", "A jam doughnut, please.",
                "Mit Pflaumenmus?", "With plum jam?",
                notes="A Pfannkuchen is a doughnut in Berlin and a pancake almost everywhere else. Ask for one in Munich and you get a pancake.",
                region="berlin",
            ),
            scene(
                "de-berlin-sc-09", "de-berlin-14", "them",
                "Somebody asks what you want to take to the park.",
                "Was nehmen wir mit?", "What are we taking?",
                "Ich mach uns Stullen.", "I'll make us some sandwiches.",
                "Perfekt, ich nehm die Decke.", "Perfect — I'll take the blanket.",
                notes="A Stulle is a buttered slice with something on it, and the word is northern. Down south it is a belegtes Brot.",
                region="berlin",
            ),
            scene(
                "de-berlin-sc-10", "de-berlin-15", "them",
                "You're walking to the next bar and someone offers to stop at the Späti on the way.",
                "Sollen wir kurz anhalten?", "Shall we stop quickly?",
                "Ja, ich hol mir ein Wegbier.", "Yes — I'll get a beer for the walk.",
                "Mir auch eins.", "Get me one too.",
                notes="Drinking in public is legal here and entirely unremarkable. The bottle opener on the Späti counter is there for exactly this.",
                region="berlin",
                difficulty="easy",
            ),
        ],
    },
    # ------------------------------------------------------------------
    "de-nightlife-slang": {
        # Kept as words: two nouns for a thing and a time, and the one for the
        # person who decides how your night goes.
        "keep": ["de-nightlife-18", "de-nightlife-19", "de-nightlife-24"],
        "scenes": [
            scene(
                "de-night-sc-01", "de-nightlife-17", "them",
                "Somebody invites you out and you want to know about the bit before.",
                "Wir sind um eins im Club.", "We'll be at the club at one.",
                "Wird vorher vorgeglüht?", "Is there pre-drinking beforehand?",
                "Ja, ab zehn bei mir.", "Yes — from ten at mine.",
                notes="Literally to pre-glow. Berlin clubs fill after midnight, so the flat beforehand is most of the evening.",
            ),
            scene(
                "de-night-sc-02", "de-nightlife-20", "them",
                "A track everybody knows comes on and your friend is still at the table.",
                "Die Nummer ist gut!", "This track's good!",
                "Komm, wir gehen abtanzen.", "Come on — let's go and dance.",
                "Ein Lied, mehr nicht.", "One song, that's it.",
                notes="Not just tanzen: abtanzen is dancing it out of your system, properly and for a while.",
            ),
            scene(
                "de-night-sc-03", "de-nightlife-21", "them",
                "It's somebody's last night in the city and nobody has plans.",
                "Was machen wir heute?", "What are we doing today?",
                "Heute machen wir einen drauf.", "Tonight we're going big.",
                "Dann schlaf ich morgen.", "I'll sleep tomorrow, then.",
            ),
            scene(
                "de-night-sc-04", "de-nightlife-22", "them",
                "It's five in the morning and somebody asks whether you're going home.",
                "Fährst du jetzt heim?", "Are you heading home now?",
                "Nee, wir machen durch.", "Nope — we're going straight through.",
                "Dann Frühstück um acht.", "Breakfast at eight, then.",
                notes="Durchmachen is going through without sleeping, and in Berlin it is often the actual plan rather than an accident.",
            ),
            scene(
                "de-night-sc-05", "de-nightlife-23", "them",
                "A tray of shots arrives and somebody is waiting for everyone to be ready.",
                "Alle so weit?", "Everybody ready?",
                "Auf ex!", "Down in one!",
                "Auf uns!", "To us!",
                notes="Ex is from the Latin. Auf ex is in one go, and it is what people say instead of counting down.",
                young=True,
            ),
        ],
    },
    # ------------------------------------------------------------------
    "de-drunk-levels": {
        # Kept as words: the neutral standard, an idiom that only works with
        # its verb, and a noun for a person past helping.
        "keep": ["de-drunk-03", "de-drunk-05", "de-drunk-09"],
        "scenes": [
            scene(
                "de-drunk-sc-01", "de-drunk-01", "them",
                "Two glasses of Sekt in, somebody checks how you're getting on.",
                "Und? Wie geht's dir so?", "So? How are you doing?",
                "Ich bin schon leicht beschwipst.", "I'm already slightly tipsy.",
                "Das Zeug hat's in sich.", "That stuff is stronger than it looks.",
                notes="From schwippen, to sway. The bottom of the scale and the nicest word on it.",
                difficulty="easy",
            ),
            scene(
                "de-drunk-sc-02", "de-drunk-02", "them",
                "A colleague at the office Christmas party asks whether you've had too much.",
                "Hast du zu viel gehabt?", "Have you had too much?",
                "Nur angeheitert, keine Sorge.", "Just merry — don't worry.",
                "Trink mal Wasser dazu.", "Have some water with it.",
                notes="The polite one, and the one to use at a work party. It says merry without admitting to drunk.",
            ),
            scene(
                "de-drunk-sc-03", "de-drunk-04", "them",
                "Somebody asks how the friend asleep in the armchair ended up there.",
                "Was ist denn mit ihm los?", "What's up with him?",
                "Der ist völlig blau.", "He's completely drunk.",
                "Wir wecken ihn gleich.", "We'll wake him in a minute.",
                notes="Literally to be blue, and nobody agrees why. Everyday, and said about somebody more often than about yourself.",
                difficulty="easy",
            ),
            scene(
                "de-drunk-sc-04", "de-drunk-06", "them",
                "It's two in the morning and somebody is already on their way to the bar for you.",
                "Noch eins für dich?", "Another one for you?",
                "Ich bin echt besoffen.", "I'm really plastered.",
                "Dann Wasser.", "Water, then.",
                notes="Informal and a bit crude, and extremely common. Betrunken is what you'd write; besoffen is what you'd say.",
            ),
            scene(
                "de-drunk-sc-05", "de-drunk-07", "them",
                "Someone asks how your night in Kreuzberg ended.",
                "Wie war's am Ende?", "How did it end up?",
                "Ich war hacke dicht.", "I was hammered.",
                "Willkommen in Berlin.", "Welcome to Berlin.",
                notes="Berlin's own, and said with a certain amount of pride. Hacke alone does the job too.",
                region="berlin",
                difficulty="hard",
            ),
            scene(
                "de-drunk-sc-06", "de-drunk-08", "them",
                "Somebody in the group can no longer stand up without help.",
                "Kannst du ihn halten?", "Can you hold him up?",
                "Er ist sturzbetrunken.", "He's falling-down drunk.",
                "Ich ruf ein Taxi.", "I'll call a taxi.",
                notes="Sturz is a fall, and the compound says exactly what it looks like.",
                difficulty="hard",
            ),
            scene(
                "de-drunk-sc-07", "de-drunk-10", "them",
                "You've hit the point where the room has stopped being interesting.",
                "Wir ziehen noch weiter, kommst du mit?", "We're going on somewhere — coming?",
                "Ich bin total durch.", "I'm completely done.",
                "Dann bring ich dich heim.", "I'll take you home, then.",
            ),
        ],
    },
    # ------------------------------------------------------------------
    "de-resacon-morning": {
        # Kept as words: the adjective that would double up with der Kater,
        # a meal, and the one that stops you driving.
        "keep": ["de-resacon-10", "de-resacon-11", "de-resacon-14"],
        "scenes": [
            scene(
                "de-resacon-sc-01", "de-resacon-09", "them",
                "You appear in the kitchen at one in the afternoon and say nothing.",
                "Guten Morgen — oder auch nicht.", "Good morning — or maybe not.",
                "Ich hab einen fetten Kater.", "I've got a monster hangover.",
                "Kaffee steht da.", "Coffee's over there.",
                notes="Der Kater is the tomcat, and the hangover both. Probably from Katarrh rather than the animal, though nobody lets that get in the way.",
                difficulty="easy",
            ),
            scene(
                "de-resacon-sc-02", "de-resacon-12", "them",
                "Somebody opens a beer at eleven the next morning and offers you one.",
                "Willst du auch eins?", "Do you want one too?",
                "Ein Konterbier, warum nicht.", "Hair of the dog — why not.",
                "Das rächt sich später.", "You'll pay for that later.",
                notes="Literally the counter-beer. The theory is disputed; the practice is widespread.",
            ),
            scene(
                "de-resacon-sc-03", "de-resacon-13", "them",
                "A friend asks what happened after midnight and you have nothing at all.",
                "Weißt du noch, was danach war?", "Do you remember what happened after that?",
                "Ich hab einen Filmriss.", "I've got a total blackout.",
                "Dann erzähl ich's dir.", "I'll tell you, then.",
                notes="Literally the film tearing mid-reel, from the days when that happened in cinemas. The most vivid word in this section.",
            ),
            scene(
                "de-resacon-sc-04", "de-resacon-15", "them",
                "You've drunk three glasses of water and are pouring a fourth.",
                "Du trinkst ja literweise.", "You're drinking by the litre.",
                "Ich hab voll den Brand.", "I'm absolutely parched.",
                "Nimm Mineralwasser.", "Have some mineral water.",
                notes="Literally to have a fire. It is the thirst specifically, not the headache.",
                difficulty="hard",
            ),
            scene(
                "de-resacon-sc-05", "de-resacon-16", "them",
                "A friend catches you swearing off alcohol for what must be the hundredth time.",
                "Wie oft hast du das jetzt gesagt?", "How many times have you said that now?",
                "Nie wieder Alkohol.", "Never again.",
                "Bis Samstag.", "See you Saturday.",
                notes="Said with total sincerity, roughly monthly.",
                difficulty="easy",
            ),
        ],
    },
}
